version: '2'
services:
  postgresql:
    image: postgres:11.7
    container_name: dojo_kleer_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dojo_kleer
      - POSTGRES_USER=dojo_kleer
      - POSTGRES_DB=dojo_kleer
  java:
    build: 
      context: ./
      dockerfile: ./docker/java/dev/Dockerfile
    container_name: dojo-kleer-java
    image: dojo-kleer
    restart: always
    command: sh run.sh
    env_file:
      - docker/java/java.env
    volumes:
      - .:/home/gradle/src
    depends_on:
      - postgresql
  nginx:
    restart: always
    image: nginx:alpine
    container_name: dojo-kleer-nginx
    volumes:
      - /home/ubuntu/www/dojo-front:/usr/share/nginx/html
      #- ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
      - "8080"
    extra_hosts:
      - "dojo-kleer.local:127.0.0.1"
    depends_on:
      - java
networks:
  default:
    external:
      name: docker_default